### ISSUE TITLE
关于训练数据TSV manifests

### ISSUE THREAD

**Issue by maomao2222** [duyichao/E2E-ST-TDA#1]
您好  您提到训练集的 TSV manifests 文件格式和fairseq官方的有所不同  那么当我使用fairseq官方的数据预处理得到manifests文件后  还需要对其进行其他的操作吗

**Comment by duyichao** [comment]
您好，
使用fairseq处理完数据之后，需要将transcription text和translation text拼在一个tsv  manifest里。后续我会把这一部分代码添加进来。

**Comment by maomao2222** [comment]
谢谢您  下面我还有一个问题  我发现训练过程中是不会输出BLEU值的  请问这是正常情况吗  只有训练完成后使用fairseq-generator命令在测试集上查看BLEU是这个意思吗

**Comment by duyichao** [comment]
> 谢谢您 下面我还有一个问题 我发现训练过程中是不会输出BLEU值的 请问这是正常情况吗 只有训练完成后使用fairseq-generator命令在测试集上查看BLEU是这个意思吗

在训练过程中不会输出BLEU值。如果想在训练中显示的话，可以在task里面加上输出BLEU Score相关的代码。

**Comment by maomao2222** [comment]
明白了  非常感谢您的解答
