### ISSUE TITLE
关于<2de>

### ISSUE THREAD

**Issue by maomao2222** [duyichao/E2E-ST-TDA#2]
您好，还是有一点问题搞不明白。
<2de>和<2en>两个标识符，需要手动加到词表txt里是吗

**Comment by duyichao** [comment]
> 您好，还是有一点问题搞不明白。
> 
> <2de>和<2en>两个标识符，需要手动加到词表txt里是吗

你好，<2de>是在训练sentence piece的时候加入的特殊符号。

**Comment by firdota** [comment]
请问，具体该怎么加呢？


> > 您好，还是有一点问题搞不明白。
> > <2de>和<2en>两个标识符，需要手动加到词表txt里是吗
> 
> 你好，<2de>是在训练sentence piece的时候加入的特殊符号。
